-- The platform's taxonomy of shops: the rows `GET /api/store-categories` answers with, and the rows
-- the panel's identity tab resolves a shop's `categoryId` against. Without them the select renders
-- "Sem categoria" for a shop that has one, because the label is looked up in an empty list.
--
-- SQL and not TypeScript. Prisma 7 runs whatever `migrations.seed` names in prisma.config.ts, and
-- apps/api has no TypeScript runner: the generated client is TypeScript that imports itself with
-- `.js` specifiers, so `node prisma/seed.ts` cannot resolve it and nothing here compiles it. One
-- statement the database itself makes idempotent is smaller than a build step, and `ON CONFLICT
-- (slug) DO UPDATE` is the upsert-on-slug the schema comment asks for: re-running this file after
-- a name, icon or colour changes corrects the row instead of failing or duplicating it.
--
-- Run it with `pnpm --filter api db:seed`, which is the only thing that runs it: on Prisma 7 neither
-- `migrate dev` nor `migrate reset` seeds, and neither says so. A reset therefore leaves this table
-- empty until you run the seed yourself — see the trap in apps/api/AGENTS.md.
--
-- It is never destructive — a slug removed from this file stays in the database, so a shop that
-- points at it keeps its category. Removing a row from the database is a separate, deliberate step.
--
-- `uuidv7()` is a Postgres 18 built-in, which is what docker-compose.yml and CI both run. The
-- column has no database default: `@default(uuid(7))` is generated by the Prisma client, so a row
-- written outside it has to bring its own id, and v7 keeps these the same shape as every other.
--
-- THE SLUGS ARE A RECONSTRUCTION. The legacy rows were typed straight into Supabase and exist in no
-- file of the legacy repository — `GET /api/categories` only ever read `store_categories`, and no
-- migration or seed in its history writes one. The import matches on `slug`, so before it runs,
-- diff this list against `SELECT slug, name FROM store_categories ORDER BY name` on the legacy
-- database and correct it here. That is a one-line edit and a re-run, by design.

INSERT INTO "store_categories" ("id", "slug", "name", "description", "icon", "color", "createdAt", "updatedAt")
VALUES
  (uuidv7(), 'alimentacao', 'Alimentação', 'Comida em geral, produtos artesanais e congelados', 'utensils-crossed', '#F97316', now(), now()),
  (uuidv7(), 'padaria', 'Padaria', 'Pães, bolos de padaria e café da manhã', 'croissant', '#F59E0B', now(), now()),
  (uuidv7(), 'doces-e-bolos', 'Doces e Bolos', 'Confeitaria, bolos por encomenda e sobremesas', 'cake', '#EC4899', now(), now()),
  (uuidv7(), 'bebidas', 'Bebidas', 'Adega, distribuidora e bebidas geladas', 'wine', '#8B5CF6', now(), now()),
  (uuidv7(), 'mercado', 'Mercado', 'Mercearia, hortifrúti e compras do dia a dia', 'shopping-basket', '#10B981', now(), now()),
  (uuidv7(), 'moda', 'Moda', 'Roupas, calçados e acessórios', 'shirt', '#EC4899', now(), now()),
  (uuidv7(), 'beleza', 'Beleza e Cosméticos', 'Cosméticos, perfumaria e cuidados pessoais', 'sparkles', '#8B5CF6', now(), now()),
  (uuidv7(), 'casa-e-decoracao', 'Casa e Decoração', 'Utilidades domésticas, móveis e decoração', 'lamp', '#14B8A6', now(), now()),
  (uuidv7(), 'eletronicos', 'Eletrônicos', 'Celulares, informática e acessórios', 'smartphone', '#3B82F6', now(), now()),
  (uuidv7(), 'petshop', 'Petshop', 'Ração, acessórios e cuidados para animais', 'paw-print', '#10B981', now(), now()),
  (uuidv7(), 'suplementos', 'Suplementos', 'Whey, creatina, vitaminas e nutrição esportiva', 'dumbbell', '#22C55E', now(), now()),
  (uuidv7(), 'saude', 'Saúde e Farmácia', 'Farmácia, produtos de saúde e cuidados pessoais', 'pill', '#14B8A6', now(), now()),
  (uuidv7(), 'servicos', 'Serviços', 'Serviços agendados, reparos e assistência', 'wrench', '#3B82F6', now(), now()),
  (uuidv7(), 'outros', 'Outros', 'Para o que não se encaixa nas demais categorias', 'store', '#8B5CF6', now(), now())
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "icon" = EXCLUDED."icon",
  "color" = EXCLUDED."color",
  "updatedAt" = now();
